version: '3.7'

services:
  curve_api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: curve_api_prod
    hostname: curve_api_prod
    environment:
      - INFURA_API_KEY
      - ALCHEMY_API_KEY_POLYGON
      - ALCHEMY_API_KEY_ETHEREUM
      - ALCHEMY_API_KEY_ARBITRUM
      - ALCHEMY_API_KEY_OPTIMISM
      - BLOCKNATIVE_API_KEY
    expose:
      - 3000
    ports:
      - "3000:3000"
