version: '3.7'

services:
  curve_api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: curve_api_dev
    hostname: curve_api_dev
    environment:
      - NODE_ENV=development
      - INFURA_API_KEY
      - ALCHEMY_API_KEY_POLYGON
      - ALCHEMY_API_KEY_ETHEREUM
      - ALCHEMY_API_KEY_ARBITRUM
      - ALCHEMY_API_KEY_OPTIMISM
      - BLOCKNATIVE_API_KEY
    volumes:
      - ./pages:/app/pages
      - ./public:/app/public
      - ./styles:/app/styles
      - ./src:/app/src
      - ./utils:/app/utils
      - ./constants:/app/constants
    expose:
      - 3000
    ports:
      - "3000:3000"
